const fakeDatabase = [
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
  {
    product_id: 1,
    product_price: 10000,
    product_price_format: "Rp50.000",
    product_name: "Payung Tokopedia",
    rating: 5.0,
    product_image: "s3.com",
    product_slug: "payung tokopedia detail",
  },
];

module.exports = fakeDatabase;
